# Generated by Django 3.0.3 on 2020-04-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpoint',
            options={'managed': False, 'verbose_name_plural': 'Endpoints'},
        ),
        migrations.AlterModelOptions(
            name='mlalgorithm',
            options={'managed': False, 'verbose_name_plural': 'ML Algorithms'},
        ),
        migrations.AlterModelOptions(
            name='mlalgorithmstatus',
            options={'managed': False, 'verbose_name_plural': 'ML Algorithms Status'},
        ),
        migrations.AlterModelOptions(
            name='mlrequest',
            options={'managed': False, 'verbose_name_plural': 'ML Requests'},
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10000)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=10000, null=True)),
                ('parent_mlalgorithm_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mlalgorithm_1', to='endpoints.MLAlgorithm')),
                ('parent_mlalgorithm_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mlalgorithm_2', to='endpoints.MLAlgorithm')),
            ],
        ),
    ]
