# Generated by Django 3.0.3 on 2020-04-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_auto_20200414_2112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endpoint',
            table='endpoints_endpoint',
        ),
        migrations.AlterModelTable(
            name='mlalgorithm',
            table='endpoints_mlalgorithm',
        ),
        migrations.AlterModelTable(
            name='mlalgorithmstatus',
            table='endpoints_mlalgorithmstatus',
        ),
        migrations.AlterModelTable(
            name='mlrequest',
            table='endpoints_mlrequest',
        ),
    ]
