# Generated by Django 3.0.3 on 2020-04-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_auto_20200414_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtest',
            name='created_by',
            field=models.TextField(),
        ),
    ]
